name: Build macOS App

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS app
      run: |
        pyinstaller project_exporter.spec
        echo "Contents of dist directory:"
        ls -R dist

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r "../项目文件导出工具-macOS.zip" "项目文件导出工具.app"
        cd ..
        echo "Contents of current directory:"
        ls -l

    - name: Get latest release
      id: get_release
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          core.setOutput('upload_url', response.data.upload_url);
          core.setOutput('release_id', response.data.id);

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./项目文件导出工具-macOS.zip
        asset_name: 项目文件导出工具-macOS.zip
        asset_content_type: application/zip

    - name: Update Release
      if: github.event_name == 'workflow_dispatch'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: ${{ steps.get_release.outputs.release_id }},
            body: 'This release has been updated with a new build on ${{ github.event.repository.updated_at }}'
          })
